#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: InLong Greeting

on:
  pull_request_target:
    types:
      - opened
  issues:
    types:
      - opened

jobs:
  greeting:
    name: Greeting
    runs-on: ubuntu-22.04
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Interact with newcomers
        uses: actions/first-interaction@v1
        continue-on-error: true
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: |
            Hello @${{ github.actor }}, thank you for submitting a PR to InLong 💖 We will respond as soon as possible ⏳
            This seems to be your first PR 🌠 Please be sure to follow our [Contribution Guidelines](https://inlong.apache.org/community/how-to-contribute).
            If you have any questions in the meantime, you can also ask us on the [InLong Discussions](https://github.com/apache/inlong/discussions) 🔍
          issue-message: |
            Hello @${{ github.actor }}, thank you for opening your first issue in InLong 🧡 We will respond as soon as possible ⏳
            If this is a bug report, please provide screenshots or error logs for us to reproduce your issue, so we can do our best to fix it.
            If you have any questions in the meantime, you can also ask us on the [InLong Discussions](https://github.com/apache/inlong/discussions) 🔍
